# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/health
Accept: application/json

###

GET http://127.0.0.1:8000/test
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/bus/realtime
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/bus/line/867
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/bus/time/0023188176816
Accept: application/json

###